services:
  postgres:

    image: postgres:latest

    environment:

      - POSTGRES_USER=${DB_USER}

      - POSTGRES_PASSWORD=${DB_PASSWORD}

    ports:
      - "1234:5432"
    
    volumes:
      - data:/var/lib/postgresql/data


volumes:
  data:
